// <auto-generated />
using System;
using InventoryManagementApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventoryManagementApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventoryManagementApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Electronic devices and accessories",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 1002,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Office and stationery products",
                            Name = "Office Supplies"
                        },
                        new
                        {
                            Id = 1003,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Networking devices and equipment",
                            Name = "Networking"
                        });
                });

            modelBuilder.Entity("InventoryManagementApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("QuantityInStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("ReorderLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products", t =>
                        {
                            t.HasCheckConstraint("CK_Products_QuantityInStock", "\"QuantityInStock\" >= 0");

                            t.HasCheckConstraint("CK_Products_ReorderLevel", "\"ReorderLevel\" >= 0");

                            t.HasCheckConstraint("CK_Products_UnitPrice", "\"UnitPrice\" >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            CategoryId = 1001,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "2.4 GHz wireless mouse",
                            Name = "Wireless Mouse",
                            QuantityInStock = 20,
                            ReorderLevel = 5,
                            Sku = "ELEC-001",
                            UnitPrice = 150000m
                        },
                        new
                        {
                            Id = 1002,
                            CategoryId = 1001,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "USB mechanical keyboard",
                            Name = "Mechanical Keyboard",
                            QuantityInStock = 15,
                            ReorderLevel = 5,
                            Sku = "ELEC-002",
                            UnitPrice = 650000m
                        },
                        new
                        {
                            Id = 1003,
                            CategoryId = 1001,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "USB headset with microphone",
                            Name = "USB Headset",
                            QuantityInStock = 12,
                            ReorderLevel = 4,
                            Sku = "ELEC-003",
                            UnitPrice = 325000m
                        },
                        new
                        {
                            Id = 1004,
                            CategoryId = 1002,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A4 paper 80 gsm",
                            Name = "A4 Paper",
                            QuantityInStock = 50,
                            ReorderLevel = 10,
                            Sku = "OFF-001",
                            UnitPrice = 65000m
                        },
                        new
                        {
                            Id = 1005,
                            CategoryId = 1002,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Blue ballpoint pen",
                            Name = "Ballpoint Pen",
                            QuantityInStock = 100,
                            ReorderLevel = 20,
                            Sku = "OFF-002",
                            UnitPrice = 5000m
                        },
                        new
                        {
                            Id = 1006,
                            CategoryId = 1002,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A5 ruled notebook",
                            Name = "Notebook",
                            QuantityInStock = 40,
                            ReorderLevel = 10,
                            Sku = "OFF-003",
                            UnitPrice = 25000m
                        },
                        new
                        {
                            Id = 1007,
                            CategoryId = 1003,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dual band wireless router",
                            Name = "WiFi Router",
                            QuantityInStock = 8,
                            ReorderLevel = 3,
                            Sku = "NET-001",
                            UnitPrice = 550000m
                        },
                        new
                        {
                            Id = 1008,
                            CategoryId = 1003,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "8 port gigabit switch",
                            Name = "Network Switch",
                            QuantityInStock = 6,
                            ReorderLevel = 2,
                            Sku = "NET-002",
                            UnitPrice = 475000m
                        },
                        new
                        {
                            Id = 1009,
                            CategoryId = 1003,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "CAT6 ethernet cable",
                            Name = "Ethernet Cable",
                            QuantityInStock = 30,
                            ReorderLevel = 10,
                            Sku = "NET-003",
                            UnitPrice = 45000m
                        },
                        new
                        {
                            Id = 1010,
                            CategoryId = 1001,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "4 port USB hub",
                            Name = "USB Hub",
                            QuantityInStock = 18,
                            ReorderLevel = 5,
                            Sku = "ELEC-004",
                            UnitPrice = 125000m
                        });
                });

            modelBuilder.Entity("InventoryManagementApi.Models.StockTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Note")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("StockTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_StockTransactions_Quantity", "\"Quantity\" <> 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            Note = "Initial stock",
                            ProductId = 1001,
                            Quantity = 20,
                            Source = 1,
                            TransactionDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 1
                        },
                        new
                        {
                            Id = 1002,
                            Note = "Initial stock",
                            ProductId = 1002,
                            Quantity = 15,
                            Source = 1,
                            TransactionDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 1
                        },
                        new
                        {
                            Id = 1003,
                            Note = "Initial stock",
                            ProductId = 1004,
                            Quantity = 50,
                            Source = 1,
                            TransactionDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 1
                        },
                        new
                        {
                            Id = 1004,
                            Note = "Initial stock",
                            ProductId = 1007,
                            Quantity = 10,
                            Source = 1,
                            TransactionDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 1
                        },
                        new
                        {
                            Id = 1005,
                            Note = "Initial sale",
                            ProductId = 1007,
                            Quantity = 2,
                            Source = 1,
                            TransactionDate = new DateTime(2026, 1, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2
                        });
                });

            modelBuilder.Entity("InventoryManagementApi.Models.Product", b =>
                {
                    b.HasOne("InventoryManagementApi.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("InventoryManagementApi.Models.StockTransaction", b =>
                {
                    b.HasOne("InventoryManagementApi.Models.Product", "Product")
                        .WithMany("StockTransactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InventoryManagementApi.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("InventoryManagementApi.Models.Product", b =>
                {
                    b.Navigation("StockTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
